# Generated by Django 5.0.4 on 2024-04-30 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('dir_admin', models.CharField(max_length=200)),
                ('colonia_admin', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('tel_admin', models.CharField(max_length=15)),
                ('email_admin', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='admin_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_repar', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('dir_repar', models.CharField(max_length=200)),
                ('colonia_repar', models.CharField(max_length=100)),
                ('tel_repar', models.CharField(max_length=15)),
                ('email_repar', models.EmailField(max_length=100)),
                ('licencia_conducir', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='repartidor_fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sucursal', models.CharField(max_length=100)),
                ('calle_sucursal', models.CharField(max_length=200)),
                ('col_sucursal', models.CharField(max_length=100)),
                ('no_exterior_sucursal', models.CharField(max_length=10)),
                ('no_interior_sucursal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_cliente', models.CharField(max_length=200)),
                ('colonia_cliente', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('tel_cliente', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('tarjeta_credito', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField()),
                ('hora', models.TimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.repartidor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ordenentrega', models.CharField(max_length=100)),
                ('fecha_actual', models.DateField()),
                ('hora', models.TimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.pedidos')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ruta', models.CharField(max_length=100)),
                ('dir_origen', models.CharField(max_length=200)),
                ('col_origen', models.CharField(max_length=100)),
                ('postal_origen', models.CharField(max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('orden_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.ordenentrega')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.repartidor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='ordenentrega',
            name='ruta_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_entrega', to='App_Lavanderia.ruta'),
        ),
        migrations.AddField(
            model_name='ordenentrega',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.sucursal'),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_titular', models.CharField(max_length=100)),
                ('fecha_ven_tarjeta', models.DateField()),
                ('nip_tarjeta', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pago', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.sucursal')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ropa', models.IntegerField()),
                ('tipo_ropa', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('detalles_extra', models.CharField(max_length=200)),
                ('dir_entrega', models.CharField(max_length=200)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.pago')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.repartidor')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='lavado_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='App_Lavanderia.tiposervicio'),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_estrellas', models.IntegerField()),
                ('comentarios', models.CharField(max_length=200)),
                ('mejoras', models.CharField(max_length=100)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.clienteregistrado')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='lavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.tiposervicio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='lavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='App_Lavanderia.tiposervicio'),
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_trans', models.CharField(max_length=100)),
                ('marca_trans', models.CharField(max_length=100)),
                ('año_trans', models.IntegerField()),
                ('color_trans', models.CharField(max_length=100)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.pedidos')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.repartidor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.sucursal')),
            ],
        ),
    ]
