# Generated by Django 5.0.4 on 2024-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creando'), ('EN', 'En espera'), ('AC', 'Aceptado'), ('TE', 'Terminado'), ('RE', 'Rechazado')], default='CR', max_length=2),
        ),
    ]
