# Generated by Django 5.0.4 on 2024-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='detalles_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalles_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
