# Generated by Django 5.0.4 on 2024-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0002_remove_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='num_tarjeta',
            field=models.CharField(default=65, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteregistrado',
            name='tarjeta_credito',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
