# Generated by Django 5.0.4 on 2024-04-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0003_remove_tarjeta_cliente_tarjeta_num_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteregistrado',
            name='tarjeta_credito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.tarjeta'),
        ),
    ]
