# Generated by Django 5.0.4 on 2024-05-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0003_detallepedido_detalles_extra_pedido_detalles_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='detalles_extra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='detalles_extra',
        ),
    ]
