# Generated by Django 5.0.4 on 2024-04-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0004_alter_clienteregistrado_tarjeta_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.pago'),
        ),
    ]
