# Generated by Django 5.0.4 on 2024-04-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0005_alter_tiposervicio_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervicio',
            name='repartidor',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='ruta',
        ),
    ]
