# Generated by Django 5.0.4 on 2024-04-30 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0006_remove_tiposervicio_repartidor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='email_repar',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='nom_repar',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='segundo_apellido',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
