# Generated by Django 5.0.4 on 2024-04-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0007_remove_repartidor_email_repar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='lavado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.tiposervicio'),
        ),
    ]
