# Generated by Django 5.0.4 on 2024-05-04 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0010_alter_administrador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='lavado',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='pago',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('ACEPTADO', 'Aceptado')], default='EN_ESPERA', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Lavanderia.pago'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='servicios',
            field=models.ManyToManyField(to='App_Lavanderia.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='lavado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='App_Lavanderia.pedidos'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='cantidad_ropa',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.RegexValidator(message='Ingrese un valor entero o medio.', regex='^\\d+(\\.5)?$')]),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='tipo_ropa',
            field=models.CharField(choices=[('Blanca', 'Ropa Blanca'), ('Negra', 'Ropa Negra'), ('Color', 'Ropa de Color'), ('Delicada', 'Ropa Delicada')], max_length=100),
        ),
    ]
