# Generated by Django 5.0.4 on 2024-05-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0011_remove_pedidos_lavado_remove_tiposervicio_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
