# Generated by Django 5.0.4 on 2024-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0012_tiposervicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='tipo_prenda',
            field=models.CharField(choices=[('Pantalones', 'Pantalones'), ('Calzones', 'Calzones'), ('Calcetines', 'Calcetines'), ('Blusas', 'Blusas')], default='Pantalones', max_length=100),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('Lavado y secado estándar', 'Lavado y secado estándar'), ('En seco', 'En seco'), ('A vapor', 'A vapor')], max_length=100),
        ),
    ]
