# Generated by Django 5.0.4 on 2024-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0014_alter_tiposervicio_tipo_prenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='detalles_extra',
            field=models.TextField(max_length=500),
        ),
    ]
