# Generated by Django 5.0.4 on 2024-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0015_alter_tiposervicio_detalles_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='tipo_prenda',
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='tipo_prenda',
            field=models.ManyToManyField(to='App_Lavanderia.tipoprenda'),
        ),
    ]
