# Generated by Django 5.0.4 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0018_alter_tiposervicio_tipo_prenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('ACEPTADO', 'Aceptado'), ('TERMINADO', 'Terminado'), ('RECHAZADO', 'Rechazado')], default='EN_ESPERA', max_length=20),
        ),
    ]
