# Generated by Django 5.0.4 on 2024-05-09 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lavanderia', '0019_alter_pedidos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='lavado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='nom_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default='Tarjeta de Crédito', max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_detalle', to='App_Lavanderia.pedidos'),
        ),
    ]
